name: Update directory hierarchy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: modify tree hierarchy for every push and commit changes
        run: |
          sed -i '/^## Structure/!b
          N;h
          :1;N
          /<\/pre>$/!b1
          s/.*\n//
          x;p
          s/.*/tree -d -L 2 -n/e
          G' README.md

          git config --global user.name ${{ secrets.USER }}
          git config --global user.email ${{ secrets.EMAIL }}

          git add .
          git commit -m "Restructured the tree" -a || true
          # The above command will fail if no changes were present, so we ignore that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
